---
name: Deploy devel documentation
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  'devel_doc':
    name: 'Update Public devel documentation'
    runs-on: ubuntu-latest
    if: github.repository == 'juliopdx/production-test'
    steps:
      - name: Checkout build repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: ./devel

      - name: Checkout docs repo
        uses: actions/checkout@v4
        with:
          repository: juliopdx/push-test
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          fetch-depth: 0
          path: ./docs

      - name: 'Setup Python 3 on runner'
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Setup Git config
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # git remote add push-test https://github.com/juliopdx/push-test
          # git fetch --all
      - name: 'Build mkdocs content and deploy'
        run: |
            ls
            cd ./docs
            pip install -r ../devel/requirements.txt
            mike deploy --push -b main devel --config-file ../devel/mkdocs.yml