---
name: Deploy devel documentation
on:
  push:
    branches:
      - devel
  workflow_dispatch:

jobs:
  'devel_doc':
    name: 'Update Public devel documentation'
    runs-on: ubuntu-latest
    if: github.repository == 'JulioPDX/production-test'
    steps:
      - name: Run dispatch
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/JulioPDX/push-test/actions/workflows/test.yml/dispatches
      # - name: Checkout build repo
      #   uses: actions/checkout@v4
      #   with:
      #     path: devel

      # - name: Checkout docs repo
      #   uses: actions/checkout@v4
      #   with:
      #     repository: JulioPDX/push-test
      #     token: ${{ secrets.REPO_ACCESS_TOKEN }}
      #     fetch-depth: 0
      #     path: docs

      # - name: 'Setup Python 3 on runner'
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.x'

      # - name: Setup Git config
      #   run: |
      #     git config --global user.name 'github-actions[bot]'
      #     git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      # - name: 'Build mkdocs content and deploy'
      #   run: |
      #       cd ./devel
      #       pip install -r requirements.txt
      #       mkdocs build -d ../docs/devel
      #       cd ../docs
      #       git add .
      #       git commit -m "updating devel with $GITHUB_SHA"
      #       git push