---
# This is deploying the latest commits on devel to aristanetworks/avd-docs main branch
name: Deploy devel documentation to aristanetworks/avd-docs main

on:
  push:
    branches:
      - devel
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  'devel_doc':
    name: 'Update Public devel documentation'
    runs-on: ubuntu-latest
    if: github.repository == 'juliopdx/production-test'
    steps:
      - name: Checkout AVD
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Setup Python 3 on runner'
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Setup Git config
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # Ninja checkout
          git remote add push-test  https://github.com/juliopdx/push-test
          # No clash with branch main
          git fetch push-test main

      - name: 'Build mkdocs content and deploy'
        run: |
            pip install -r requirements.txt
            mike deploy --push -r push-test -b main devel